[package]
name = "anagram"
version = "0.1.0"
edition = "2021"
authors = ["SaitoAtsushi <maldikulo@gmail.com>"]
description = "A anagram searcher"
license = "MIT"

[dependencies]
num-bigint = "0.4.4"
num-traits = "0.2.16"

[profile.release]
lto = true
opt-level = 3
strip = true
